name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  code-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Run lint
      run: npm run lint
      env:
        CI: true

    - name: Run tests
      run: npm run test:cov
      env:
        CI: true

    - name: Check code coverage
      run: |
        echo "Checking code coverage..."
        coverage=`cat coverage/lcov.info | grep -o 'Lines.*' | awk '{ print $3 }'`
        coverage=${coverage%\%}
        if (( $(echo "$coverage < 60" | bc -l) )); then
          echo "Error: Code coverage is less than 60%. Actual coverage is $coverage%"
          exit 1
        fi
        echo "Code coverage is sufficient ($coverage%)."

    - name: Build
      run: npm run build

    - name: Publish test report
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v1
      with:
        name: jest-html-report
        path: jest_html_reporters
